name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm install, build
      run: |
        npm ci
        npm run build
        touch ./dist/.nojekyll
        sed -i '/\/dist/d' .gitignore
        echo "map-tile-compare.leifgehrmann.com" >> ./dist/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        force_orphan: true
