name: NPM Audit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1'

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - name: Run audit
        run: |
          npm audit --production
