name: NPM Audit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 1'

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Run audit
        run: |
          npm audit --production
